# Generated by Django 2.2.10 on 2021-12-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='started_at',
            field=models.DateTimeField(editable=False, verbose_name='date started'),
        ),
    ]
