# Generated by Django 2.2.10 on 2021-12-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211208_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='started_at',
            field=models.DateTimeField(verbose_name='date started'),
        ),
    ]
