# Generated by Django 2.2.10 on 2021-12-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211208_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_type',
            field=models.CharField(choices=[('TEXT', 'Text answer'), ('SELECT', 'Select answer'), ('MULTISELECT', 'Multiselect answer')], default='TEXT', max_length=10),
        ),
    ]
