# Generated by Django 2.2.10 on 2021-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20211209_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_type',
            field=models.CharField(choices=[('TEXT', 'Text answer'), ('SELECT', 'Select answer'), ('MULTISELECT', 'Multiselect answer')], max_length=11),
        ),
    ]
