# Generated by Django 2.2.10 on 2021-12-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20211209_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
