# Generated by Django 2.2.10 on 2021-12-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
