# Generated by Django 2.2.10 on 2021-12-09 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20211209_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 17, 31, 20, 957091, tzinfo=utc), editable=False),
        ),
    ]
