# Generated by Django 2.2.10 on 2021-12-12 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20211209_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 11, 53, 10, 533903, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
